# Generated by Django 5.2.6 on 2025-09-11 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=30)),
                ('cargo', models.CharField(max_length=50)),
                ('salario', models.FloatField()),
                ('descricao', models.TextField()),
                ('data_nascimento', models.DateField()),
                ('data_admissao', models.DateField()),
                ('status', models.CharField(default='ativo', max_length=20)),
            ],
            options={
                'db_table': 'funcionarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SiteVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_site', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('vendido', 'Vendido'), ('desenvolvimento', 'Em Desenvolvimento')], default='disponivel', max_length=20)),
            ],
            options={
                'db_table': 'sites_venda',
            },
        ),
        migrations.CreateModel(
            name='PedidoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=100)),
                ('cliente_email', models.EmailField(max_length=254)),
                ('cliente_telefone', models.CharField(max_length=20)),
                ('mensagem', models.TextField(blank=True)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('concluido', 'Concluído')], default='pendente', max_length=20)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sitevenda')),
            ],
            options={
                'db_table': 'pedidos_sites',
            },
        ),
    ]
