# Generated by Django 5.2.6 on 2025-09-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioDeletado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_funcionario_original', models.IntegerField()),
                ('nome', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=30)),
                ('cargo', models.CharField(max_length=50)),
                ('salario', models.FloatField()),
                ('descricao', models.TextField()),
                ('data_nascimento', models.DateField()),
                ('data_admissao', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('data_exclusao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'funcionarios_deletados',
            },
        ),
    ]
